name: .NET

on:
  push:
    branches: [ main ]
  pull_request:

env:
  DOTNET_VERSION: '3.1.x'
  CONFIGURATION: 'Release'
  PROJECT_ROOT: 'simple-rpg-game'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_ROOT }}/

    - name: Build
      run: dotnet build ${{ env.PROJECT_ROOT }}/ --no-restore --configuration ${{ env.CONFIGURATION }}

    - name: Test
      run: dotnet test ${{ env.PROJECT_ROOT }}/ --no-build --verbosity normal
